/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sohu.cloudatlas.services;

public class cloudatlasConstants {

	public static final String VERSION = "1.0.0";

}
